spring.application.name=ex01
spring.datasource.url=jdbc:postgresql://localhost:5432/md03_ss15
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
jwt.secret-key=milk-tea-shop-jwt-secret-key-at-least-32-bytes-long
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
